apiVersion: v1
kind: Service
metadata:
  name: $K8S_DEPLOYMENT_NAME
  labels:
    name: $K8S_DEPLOYMENT_NAME
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: $K8S_DEPLOYMENT_NAME
    role: $TARGET_ROLE
